In [142]:
import numpy as np
from sklearn import svm
from sklearn.metrics import accuracy_score
import urllib

from scipy.sparse import coo_matrix
from sklearn.utils import shuffle

from sklearn import preprocessing

import matplotlib.pyplot as plt
%matplotlib inline

#Load wines data
rawdata = urllib.urlopen('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data')
dataset = np.loadtxt(rawdata, delimiter=",")

In [143]:
print(dataset.shape)

(178, 14)


In [144]:
# Get first column to be target; the rest are features
T = dataset.T
target = T[0]
data = T[1:].T

In [145]:
# Shuffle data
x_sparse = coo_matrix(data)
x, x_sparse, y = shuffle(data, x_sparse, target, random_state=0)

In [146]:
# Perform preprocessing by scaling; without it, accuracy is > 0.3
x = preprocessing.scale(x)
x

array([[ 0.91333271, -0.59815632, -0.42590882, ..., -0.16430337,
         0.83096074,  0.99708646],
       [-0.26016901,  0.29950682,  0.41481959, ..., -2.09473241,
        -1.61256533, -0.84991991],
       [-0.77898029, -1.08289442, -0.75488951, ...,  1.15189824,
         0.36485461, -1.04098953],
       ..., 
       [-0.71721705, -0.65201611, -0.64522928, ...,  0.44992405,
         0.49197446, -1.27982657],
       [ 1.1109751 , -0.58917969, -0.90110314, ..., -0.20817676,
         1.01457831,  0.75824943],
       [ 1.43214399,  0.15588072,  0.41481959, ..., -1.48050498,
        -1.27357906, -0.27671104]])

In [147]:
# Setup number of training data
n_train = 120

In [148]:
clf = svm.SVC(decision_function_shape='ovo')
pred = clf.fit(x[:n_train], y[:n_train]).predict(x[n_train:])

In [149]:
pred

array([ 2.,  2.,  1.,  1.,  1.,  3.,  2.,  1.,  2.,  3.,  1.,  2.,  3.,
        3.,  1.,  1.,  3.,  1.,  3.,  2.,  1.,  1.,  2.,  1.,  3.,  2.,
        3.,  1.,  3.,  3.,  3.,  1.,  2.,  2.,  2.,  2.,  3.,  3.,  2.,
        2.,  2.,  2.,  3.,  3.,  1.,  1.,  3.,  2.,  2.,  2.,  1.,  1.,
        1.,  2.,  2.,  2.,  1.,  3.])

In [150]:
y[n_train:]

array([ 2.,  2.,  1.,  1.,  1.,  3.,  2.,  1.,  2.,  3.,  1.,  2.,  3.,
        3.,  1.,  1.,  3.,  1.,  3.,  2.,  1.,  1.,  2.,  1.,  3.,  2.,
        3.,  1.,  3.,  3.,  3.,  1.,  2.,  2.,  2.,  2.,  3.,  3.,  2.,
        2.,  1.,  2.,  3.,  3.,  1.,  1.,  3.,  2.,  2.,  2.,  1.,  1.,
        1.,  2.,  2.,  2.,  1.,  3.])

In [151]:
accuracy_score(y[n_train:], pred)

0.98275862068965514